import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';
import type { Composition, Scene } from '../state/project-state.js';

// ESM doesn't have __dirname — derive from import.meta.url
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Validate that projectPath is a legitimate Remotion project directory.
// Call this at the top of every tool handler except start_session and init_project.
export async function validateProjectPath(projectPath: string): Promise<void> {
  const resolved = path.resolve(projectPath);

  if (projectPath.includes('..')) {
    throw new Error(`Project path must not contain '..': ${projectPath}`);
  }

  // Reject obviously dangerous system paths
  const dangerous = ['/', '/usr', '/etc', '/var', '/tmp', '/bin', '/sbin'];
  if (dangerous.includes(resolved) || resolved === process.env.HOME) {
    throw new Error(`Refusing to operate on system directory: ${resolved}`);
  }

  // Verify composition.json exists (confirms this is an initialized project)
  const compositionPath = path.join(resolved, 'composition.json');
  if (!await fs.pathExists(compositionPath)) {
    throw new Error(
      `No composition.json found at ${resolved}. Did you run init_project first?`
    );
  }
}

// Create all directories needed for a new project
export async function ensureProjectDirs(projectPath: string): Promise<void> {
  const dirs = [
    'assets/images',
    'assets/audio',
    'assets/fonts',
    'scenes',
    'src/templates',
    'src/utils',
    'public',      // Remotion's staticFile() serves from public/
    'output',
  ];
  for (const dir of dirs) {
    await fs.ensureDir(path.join(projectPath, dir));
  }

  // .gitkeep files so empty dirs are committed
  const keepDirs = ['assets/images', 'assets/audio', 'assets/fonts', 'output'];
  for (const dir of keepDirs) {
    await fs.writeFile(path.join(projectPath, dir, '.gitkeep'), '');
  }

  // Symlink public/ subdirs to assets/ so staticFile() can find them
  const assetDirs = ['images', 'audio', 'fonts'];
  for (const dir of assetDirs) {
    const target = path.join(projectPath, 'assets', dir);
    const link = path.join(projectPath, 'public', dir);
    if (!await fs.pathExists(link)) {
      try {
        await fs.symlink(target, link, process.platform === 'win32' ? 'junction' : 'dir');
      } catch {
        // Fallback: copy instead of symlink
        await fs.copy(target, link);
      }
    }
  }
}

// Copy template files from the MCP server's src/templates/ into the user project.
// Root.tsx is NOT copied — it's always generated by regenerateRootTsx().
export async function copyTemplates(
  projectPath: string,
  serverRoot: string
): Promise<void> {
  const templatesDir = path.join(serverRoot, 'src', 'templates');

  // SceneRenderer copied once and never regenerated
  await fs.copy(
    path.join(templatesDir, 'SceneRenderer.tsx'),
    path.join(projectPath, 'src', 'SceneRenderer.tsx')
  );

  // Component templates → src/templates/
  await fs.copy(
    path.join(templatesDir, 'components'),
    path.join(projectPath, 'src', 'templates')
  );

  // Utility helpers → src/utils/
  await fs.copy(
    path.join(templatesDir, 'utils'),
    path.join(projectPath, 'src', 'utils')
  );
}

// The server's own root directory — used to locate src/templates/ at runtime.
// After compile: __dirname = dist/utils/, so go up two levels to project root.
export function getServerRoot(): string {
  return path.join(__dirname, '..', '..');
}

// Generate a scene's .tsx file content from its composition.json entry
export function generateSceneTsx(scene: Scene, composition: Composition): string {
  const componentName = sceneIdToComponentName(scene.id);

  if (scene.type === 'custom') {
    // Custom scenes render objects via AnimatedObject
    return `import React from 'react';
import { AbsoluteFill } from 'remotion';
import { AnimatedObject } from '../src/templates/AnimatedObject';

// Auto-generated from composition.json — do not edit directly
export const ${componentName}: React.FC = () => {
  const objects = ${JSON.stringify(scene.objects ?? [], null, 2)};
  const backgroundColor = ${JSON.stringify((scene.props as Record<string, unknown>)?.backgroundColor ?? '#000000')};

  return (
    <AbsoluteFill style={{ backgroundColor }}>
      {objects.map((obj: { id: string; [key: string]: unknown }) => (
        <AnimatedObject key={obj.id} object={obj} />
      ))}
    </AbsoluteFill>
  );
};
`;
  }

  // Named template types — pass props directly to the matching component
  const componentImport = sceneTypeToImport(scene.type);
  return `import React from 'react';
import { ${componentImport} } from '../src/templates/${componentImport}';

// Auto-generated from composition.json — do not edit directly
export const ${componentName}: React.FC = () => {
  const props = ${JSON.stringify(scene.props ?? {}, null, 2)};
  return <${componentImport} {...props} />;
};
`;
}

// Write a scene's .tsx file to the scenes/ directory
export async function writeSceneFile(
  projectPath: string,
  scene: Scene,
  composition: Composition
): Promise<void> {
  const filePath = path.join(projectPath, scene.file);
  await fs.ensureDir(path.dirname(filePath));
  await fs.writeFile(filePath, generateSceneTsx(scene, composition));
}

// Regenerate Root.tsx from the current scenes array.
// Called after any scene mutation so the composition always reflects reality.
//
// Audio paths stored in composition.json must be relative to public/, NOT assets/.
// e.g. "audio/voiceover.mp3" → staticFile('audio/voiceover.mp3') → public/audio/voiceover.mp3
export async function regenerateRootTsx(
  projectPath: string,
  composition: Composition
): Promise<void> {
  const { settings, scenes, audio } = composition;
  const overlays = (composition.overlays ?? []).sort((a, b) => a.zIndex - b.zIndex);

  // Guard against zero-duration — Remotion rejects durationInFrames: 0
  const totalFrames =
    settings.totalDurationFrames ??
    (scenes.reduce((sum, s) => sum + s.durationFrames, 0) || 1);

  const sceneImports = scenes
    .map((s) => {
      const name = sceneIdToComponentName(s.id);
      return `import { ${name} } from '../scenes/${path.basename(s.file, '.tsx')}';`;
    })
    .join('\n');

  const seriesEntries = scenes
    .map((s) => {
      const name = sceneIdToComponentName(s.id);
      return `      <Series.Sequence durationInFrames={${s.durationFrames}}>\n        <${name} />\n      </Series.Sequence>`;
    })
    .join('\n');

  // Audio JSX — <Audio> from @remotion/media, staticFile() from remotion
  const hasAudio = audio.type !== 'none';
  const audioImport = hasAudio ? `import { Audio } from '@remotion/media';\nimport { staticFile } from 'remotion';` : '';

  let audioJsx = '';
  if (audio.type === 'narration' && audio.narration) {
    const narrationFile = (audio.narration as Record<string, unknown>).file as string;
    audioJsx += `\n        {/* Narration audio — synced to scene timeline */}\n        <Audio src={staticFile('${narrationFile}')} />`;
  }
  if (audio.backgroundMusic) {
    const bgMusic = audio.backgroundMusic as Record<string, unknown>;
    const bgFile = bgMusic.file as string;
    const volume = bgMusic.volume ?? 0.15;
    const loop = bgMusic.loop ?? true;
    audioJsx += `\n        {/* Background music */}\n        <Audio\n          src={staticFile('${bgFile}')}\n          volume={${volume}}\n          loop={${loop}}\n        />`;
  }

  // Overlay imports — each overlay is a named export from a project-relative file
  const overlayImports = overlays
    .map((o) => `import { ${o.componentName} } from '../${o.file.replace(/\.tsx$/, '')}';`)
    .join('\n');

  // Overlay render blocks — full-duration or partial-duration (wrapped in <Sequence>)
  const overlayRenderBlocks = overlays
    .map((o) => {
      const inner =
        `      <AbsoluteFill style={{ zIndex: ${o.zIndex}, pointerEvents: 'none' as const }}>\n` +
        `        <${o.componentName} />\n` +
        `      </AbsoluteFill>`;
      // Partial-duration overlays wrapped in <Sequence>
      if (o.startFrame != null || o.endFrame != null) {
        const from = o.startFrame ?? 0;
        const durationProp = o.endFrame != null ? ` durationInFrames={${o.endFrame - from}}` : '';
        return `      {/* Overlay: ${o.name} (frames ${from}–${o.endFrame ?? 'end'}) */}\n` +
          `      <Sequence from={${from}}${durationProp}>\n${inner}\n      </Sequence>`;
      }
      return `      {/* Overlay: ${o.name} — full duration */}\n${inner}`;
    })
    .join('\n');

  // Conditionally add AbsoluteFill and Sequence to remotion imports when overlays exist
  const hasPartialOverlays = overlays.some((o) => o.startFrame != null || o.endFrame != null);
  const remotionImports = overlays.length > 0
    ? `Composition, Series, AbsoluteFill${hasPartialOverlays ? ', Sequence' : ''}`
    : 'Composition, Series';

  const rootContent = `import React from 'react';
import { ${remotionImports} } from 'remotion';
${hasAudio ? audioImport : ''}
${sceneImports}
${overlayImports}

// Auto-generated from composition.json — do not edit directly
export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="main"
        component={MainComposition}
        durationInFrames={${totalFrames}}
        fps={${settings.fps}}
        width={${settings.width}}
        height={${settings.height}}
      />
    </>
  );
};

const MainComposition: React.FC = () => {
  return (
    <>
      <Series>
${seriesEntries}
      </Series>${audioJsx}
${overlayRenderBlocks}
    </>
  );
};
`;

  await fs.writeFile(path.join(projectPath, 'src', 'Root.tsx'), rootContent);
}

// "scene-001" → "Scene001", "001-intro" → "Scene001Intro"
export function sceneIdToComponentName(sceneId: string): string {
  let result = sceneId
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
  // JSX component names must start with uppercase letter, not digit
  if (/^\d/.test(result)) result = 'Scene' + result;
  return result;
}

// "title-card" → "TitleCard"
function sceneTypeToImport(sceneType: string): string {
  return sceneType
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}
